# 问题集合
### promise问题
```
1. 关于resolvePromise多次调用问题
2. callBack函数存放到[]的作用
3. 循环callBack回调函数时，try...catch.. 中使用 throw new Error("成功函数有误!") 直接报错问题、
4. resolvePromise 中当返回的数据(res instanceof MyPromise) 时当res.status == "pending" 的处理问题
```